### ISSUE TITLE
Provide clearer error messages

### ISSUE THREAD

**Issue by florianm** [opendatakit/central#104]
As a budding ODK Central maintaner, I'd love to get more verbose error messages. My main error source is mis-configuration of e.g. database parameters used by ODKC through two layers of libraries.

* When restarting the backend (service), I need to restart the frontend (nginx). If not, the frontend will raise the error "no route to service". In that case, I'd love to get a GUI error message saying "Frontend cannot find backend server. Please tell your sysadmin to restart the frontend container". This message should also go to Sentry.
* Email errors. Still struggling to get email to work (with settings that work from other containers in same cluster without problems), so I'm permutating the connection settings as per https://nodemailer.com/smtp/ - would be super helpful to just see the plain error message in the GUI when trying to send an email (e.g. inviting new users, resetting password for a user). See https://nodemailer.com/smtp/#verify-smtp-connection-configuration as a startup check sent to logs and Sentry.

I found some error messages for known errors in `lib/util/problem.js`, but I'm getting e.g. on email sending failure "Something went wrong: the server returned an invalid error.".

* Would it be possible to support self-hosted Sentry instances? Current settings default to sentry.io.

**Comment by issa-tseng** [comment]
hi @florianm: can you please clarify your ask here, given your comments elsewhere?
in general, requests around nonstandard installations will be less likely to receive my time.

**Comment by florianm** [comment]
Re sentry: see #106 

Re random (or any) errors: could the original error message be shown in addition ("expand details") to the messages from `lib/util/problem.js`?

Re email errors: Could the error, if found at the startup check as per https://nodemailer.com/smtp/#verify-smtp-connection-configuration, be sent to Sentry/shown as error message?

All of there are only suggestions for minor improvements (specifically where I bumped my head), so I'm happy for these to go to the bottom of the pile.

**Comment by issa-tseng** [comment]
> Re random (or any) errors: could the original error message be shown in addition ("expand details") to the messages from `lib/util/problem.js`?

they already are, though? in what context are you looking for the details? right now the details are always returned over the wire.

> Re email errors: Could the error, if found at the startup check as per https://nodemailer.com/smtp/#verify-smtp-connection-configuration, be sent to Sentry/shown as error message?

sending to Sentry is not a great idea because all it means is that i get more notifications that i can't do anything about. showing as an error message would be more useful, but that's quite a lot of plumbing, and you run into difficult questions like "who exactly should see this error message and when?" in general, we're also likely going to move the default email setup to something that's even more sandboxed and hands-off for common installs than what we have right now, so i would be surprised if many people encounter problems with email now or in the future.

**Comment by florianm** [comment]
That rationale works for me. As explained above, I got stuck with db/email/restarting sequence which should be fine for standard installs, and others might find my notes here. Closing as "good enough as is".
