### ISSUE TITLE
Odata connection to Ethercalc?

### ISSUE THREAD

**Issue by poVoq** [opendatakit/central#21]
For fully (offline) selfhosted setups it might be very usefull to be able to connect to a Ethercalc instance.
Ethercalc also supports some pretty cool web-form features, so a lot of nice functionality similar to Enketo could be quickly proto-typed with it.

I created an entry for possible support of odata here (although it might be that one of the already integrated libs already supports it):
https://github.com/audreyt/ethercalc/issues/642

Since it is also a nodejs app, maybe someone here would be interested in looking into this connection?

Thanks a lot!

Edit: Selfhosting is really easy with the official docker image: https://hub.docker.com/r/audreyt/ethercalc/

**Comment by clint-tseng** [comment]
Hey, Ethercalc is really cool; thanks for sharing it with us, and great great work on it @audreyt!

I can't tell from skimming the docs whether it has an architecture that would allow eg some notion of an updatable/reimportable base truth on top of which a set of saved analysis could be reapplied—it seems like it wants to be its own source of truth instead, and updates should be made directly to its spreadsheet. Part of the value proposition of OData is that the data is live, and so any analysis you build would continually reflect the latest information; if Ethercalc owns its own truth once the data is first imported this advantage loses its edge.

That said, another part of the value proposition is the somewhat richer schema information it provides than eg CSV without the proprietary encumbrance of eg XLS(X). So in that regard the feature may still have value for that reason.

I would, however, pretty strongly discourage using both ODK _and_ Ethercalc webforms, because suddenly you'll have two separate notions of truth that will compete with each other, and I suspect you'll not be happy with the result.

Finally, while we'd wholeheartedly recommend Ethercalc to our users as an analysis option if integration does work out well, I'm not sure what the ask is of us at this moment, and therefore I'm not sure what the utility of this issue ticket is, exactly. Is there something specific you had in mind?

**Comment by eddyparkinson** [comment]
@poVoq are you thinking of adding OData style functionality to ethercalc?   Happy to support this. 

I assume you know ethercalc keeps a history log of changes to the spreadsheet.

**Comment by issa-tseng** [comment]
i still think this is a good idea, but we provide a reference-compatible OData output feed, and so it seems like the work here is not on our side.

if anybody takes this on in the future, i'm happy to answer questions and resolve issues, but for now i am closing this ticket.
