### ISSUE TITLE
Deleting forms and reuploading the same one resulted in error

### ISSUE THREAD

**Issue by arkhub** [opendatakit/central#39]
It shown errors that previous form already exist (although I've deleted it previously in odk central web) : 

![error-01](https://user-images.githubusercontent.com/3181536/50495042-435c4b80-0a59-11e9-9eab-ba1694a28c91.JPG)

I only managed to reuploaded after changing the form_id, converted it to xml and re-upload it again.

**Comment by clint-tseng** [comment]
as described in the message, this is intentional. you _must_ change either the form id or the version in order to upload the same form again.

this is because if somebody has already downloaded the form to their mobile device before you deleted it from the server, and then you create a new different form with the same form id and version, then there is no way for the system to know that the form on the device is different than the form on the server when submissions to the form are uploaded, and data can get mixed and confused.

**Comment by arkhub** [comment]
oh ok, that's make sense although I wish I can override it while still in development mode. Is it possible if i redownload the docker images or delete the specific data from the posgres db directly?

**Comment by clint-tseng** [comment]
yeah—eventually if/when we have form preview on the central web panel itself, we may introduce some sort of draft state where you can replace over a form as many times as you'd like because it won't be visible for download onto mobile devices.

for right now, you can delete the data from postgres directly, yes: you can log into postgres with this command:

`docker-compose exec postgres psql -U odk -W odk`

and giving the password (by default also just `odk`). then you can cascading-delete the appropriate records from the `forms` table.

**Comment by arkhub** [comment]
thanks, I've managed to delete the previous form now.
