### ISSUE TITLE
Add R/ruODK link to documentation+odata dialog

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/central#72]
Inspired by https://forum.opendatakit.org/t/odk-central-v0-5-beta/19647/2

I think we should link to some freer OData tools that let users analyze their data. The first step in the process is to verify that our feed works with those tools.

**Comment by issa-tseng** [comment]
i think step one for R would be to pick from the dozens (hundreds) of packages related to this task..

i think someone asked about R before, though, and i think at the time i mentioned that since OData is just JSON there are plenty of ways to deal with our feeds in R.

**Comment by issa-tseng** [comment]
it looks like libreoffice has neither odata nor json support.

**Comment by florianm** [comment]
@yanokwa thanks for picking this topic up.

My use case: 

* I want to switch from Aggregate to Central. 
* For my own purpose, I'll want to read the data from OCK Central into R in order to do the ETL into my data warehouse.
* For simple use cases, I want to present my end users with a simple entry point to automate their ODK Central ETL. For this, the "export all submissions" is a fantastic start point, as it flattens out all repeating groups, and includes media (photos). Streaming via OData would be more automated.

Testing access pathways:

* Plain old R works nicely. Just whack that OData service URL over the head with `httr`and flatten the nested list of lists with `tidyr::unnest_wide`. Here's an [example](https://rpubs.com/florian_mayer/spotlighting) - so far without repeating form subgroups or pagination of results.
* [OData](https://cran.r-project.org/web/packages/OData/index.html) has pretty sparse [documentation](https://www.rdocumentation.org/packages/OData/versions/0.6) and doesn't support authentication, resulting in 403 errors. [The OData source](https://rdrr.io/cran/OData/src/R/OData.R) shows at least the rudimentary steps.
* [odataR](https://github.com/HanOostdijk/odataR) looks more promising, but haven't got that to work yet. What's Central's base URL for the OData service? Why does `odataR` not use the .svc URL? 
* LibreOffice ([v6.2 on Ubuntu 18.04](http://tipsonubuntu.com/2018/08/11/install-libreoffice-6-1-ubuntu-18-04-16-04/)) has an OData module in the [source](https://github.com/LibreOffice/core/blob/master/io/source/stm/odata.cxx), but for the life of me, I can't seem to find out how to open OData:

  * File > Open remote > Add service: no OData.
  * Data > Streams using (any subset of) the ODK Central OData .svc URL won't enable the "OK" button. To unlock "Streams", I had to change the JRE in the settings.

* PowerBI looks great, but on my non-Windows machine, only the PowerBI web app is available (and that only because my employer pays for it, so that's not exactly an open access option for my external collaborators) which unfortunately doesn't support OData. Our IT folks are looking into setting up a [gateway](https://community.powerbi.com/t5/Integrations-with-Files-and/Power-BI-Web-app-pull-data-from-Odata-API/m-p/296923#M13930) which might or might not work. Even though it won't work for my use case, PowerBI/Tableau support is a great feature to include non-technical data consumers!

**Comment by issa-tseng** [comment]
i just looked at ruODK again and it's looking mighty fine so i think we're in a good spot already to add it to the compendium.

we'll want to add information about it in three spots:
* the API documentation
* the user documentation
* the odata popup dialog

as for the popup dialog, check with me and i'll come up with a UI and some wording for it.

**Comment by florianm** [comment]
Cheers @issa-tseng! I'm working on supporting the other API endpoints too, beginning with the "give me my data" use cases.
Suggestions and ideas always welcome!

**Comment by matthew-white** [comment]
We now have ruODK in the OData modal! See https://github.com/opendatakit/central-frontend/pull/240. @issa-tseng, I'm going to assign this issue to you, but let me know if you need anything else from my end.
